replicaCount: 1

names:
  deployment: nginx-app
  service: nginx-app
  ingress: nginx-app

image:
  repository: aksmgd/nginx_dockerhub   
  tag: "latest"                            
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  host: my-nginx.local
