apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.deployment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.names.deployment }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.deployment }}
    spec:
      containers:
        - name: {{ .Values.names.deployment }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
